name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    environment: fetch-tools
    strategy:
      matrix:
        python-version: [3.8]
        subset:
         - test.list
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirement
        run: python -m pip install -r requirements.txt
      - name: Test tool extraction
        # run: bash bin/extract_all_tools.sh
        run: | 
          bash ./bin/extract_all_tools_test.sh "${{ matrix.subset }}"
        env: 
          GITHUB_API_KEY: ${{ secrets.GH_API_TOKEN }}
      - name: Test tutorial extraction and filtering
        run: | 
          bash ./bin/extract_filter_tutorials_test.sh
        env: 
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_TOKEN }}